### ISSUE TITLE
nix-shell dependencies not updated during nixos-rebuild

### ISSUE THREAD

**Issue by Guest0x0** [nix-community/nix-direnv#110]
# Synpothesis
Derivations that are (only) referenced by some nix-shell (.envrc) are not upgraded during `nixos-rebuild --upgrade`, while the nixpkgs channel is upgraded. So a rebuild will be triggered when entering those `direnv` guarded directories.

According to my understanding, `nixos-rebuild` only builds the user environment defined by `/etc/nixos/configuration.nix`, so other gc-roots are not rebuilt.

My nix-direnv version is `1.2.6`, from nixpkgs 21.05.

# Desired behavior
Direnv referenced derivations also get upgraded on `nixos-rebuild`,  or can get upgraded altogether through some separate utility (like `home-manager` does).

**Comment by Mic92** [comment]
Direnv cache should get invalidated as soon as your nixpkgs channel sees an upgrade:

https://github.com/nix-community/nix-direnv/blob/45f3927ab5a687f4d374f7e370fe002d8f11822e/direnvrc#L194

Otherwise you can always trigger updates by running `touch default.nix` or `touch shell.nix`: https://github.com/nix-community/nix-direnv#manually-re-triggering-evaluation

**Comment by Guest0x0** [comment]
I have created a snippet to automatically perform such updates:
```
nix-store --gc --print-roots \
    | grep ".direnv" \
    | awk '{ sub(".direnv/drv$", "", $1); print "direnv exec "$1" true;"  }' \
    | sh
```
Not sure if this is robust enough though.

I am trying to hook the snippet into `home-manager switch`, but that's no longer an issue for `nix-direnv`, so I'll close this issue.
