### ISSUE TITLE
sed errors upon entering cached environment

### ISSUE THREAD

**Issue by winterqt** [nix-community/nix-direnv#120]
An error like this appear whenever entering a cached environment. The environment loads successfully, so I'm not really sure what's causing this. This occurs with and without a custom `direnv_layout_dir` function.

```
sed: inter/.cache/direnv/layouts/b23089093f0f1d542fd08f3f5d0fe66e74b0c56f/flake-profile-a5d5b61aa8a61b7d9d765e1daf971a9a578f1cfa.rc: No such file or directory
```

`nix-direnv` version: 1.5.0

**Comment by Mic92** [comment]
This originates from `use nix`. The sed command patches the resulting rc file from `nix print-dev-env` in:
https://github.com/nix-community/nix-direnv/blob/a3d08b6c8fa2a976aba430c733f54cf97d9046b0/direnvrc#L155

If you don't have this file your environment should not be loaded, so what is in your `.envrc`?

**Comment by winterqt** [comment]
I should've clarified that I'm using flakes, sorry.

My `.envrc` is ```
use flake
```

**Comment by winterqt** [comment]
Additionally, I added `set -x`s to debug, and this is just really strange:

```
++ sed -i '/eval "$shellHook"/d' /Users/winter/Downloads/nix-direnv-sed/.direnv/flake-profile-a5d5b61aa8a61b7d9d765e1daf971a9a578f1cfa.rc
sed: inter/Downloads/nix-direnv-sed/.direnv/flake-profile-a5d5b61aa8a61b7d9d765e1daf971a9a578f1cfa.rc: No such file or directory
```

Is the argument somehow... being substringed? Very strange.

**Comment by winterqt** [comment]
Putting GNU's `sed` in my `PATH` fixes this. (I was previously using the Apple provided `sed`.)

Very, very strange.

**Comment by Mic92** [comment]
Ok. I see the issue now. Apple's `sed` does not support `-i`.

**Comment by lilyball** [comment]
I just hit this today. It was very confusing. Apple's `sed` supports `-i` but it takes a required backup extension as a separate arg, whereas gnused expects it to be attached to the flag (e.g. `-i[SUFFIX]` or `--in-place[=SUFFIX]`).

This is such an annoying incompatibility between BSD sed and GNU sed. One option is to just accept the backup and delete it (e.g. `sed -i.bak ' -e '/eval "$shellHook"/d' "$profile_rc"`), though cleaning it up reliably in the face of an error while still propagating the error is annoying. Another option is to ditch sed and use something like `perl -ni -e 'print unless /eval "\$shellHook"/'`. `perl` is pretty darn ubiquitous. I know Apple has deprecated most scripting languages, but since Perl doesn't have a built-in REPL it's hard to tell if that's included in the deprecation. It should at least work for now.

**Comment by lilyball** [comment]
My current workaround is

```nix
{
  programs.direnv = {
    stdlib = ''
      sed() { ${pkgs.gnused}/bin/sed "$@"; }
    '';
  };
}
```

**Comment by winterqt** [comment]
@lilyball Both the Perl script and the `sed` override in direnv stdlib are great solutions to this. Thank you!

(This isn't the first time that I've seen you come up with nice solutions for Nix + macOS issues, and I appreciate it.)
