### ISSUE TITLE
Reevaluation caused by modifying default.nix even when shell.nix is present

### ISSUE THREAD

**Issue by lheckemann** [nix-community/nix-direnv#147]
I have a project whose root contains both `shell.nix` (which, as expected, is used by nix-direnv) and `default.nix`. Whenever I modify `default.nix`, the environment is reevaluated, even though this is not necessary. nix-direnv should check for updates only on the file it's actually going to use.

**Comment by Mic92** [comment]
A potential work around would be also to use https://github.com/nix-community/nix-direnv/pull/145
but in general you are right.

**Comment by bbenne10** [comment]
I would also point you at #148 as a potential fix. If you're interested in a particular fix, please comment on them with your preferences so we can figure out which is the best for the active community. Thank you.

**Comment by bbenne10** [comment]
#148 has been merged. Please check that out and report back?

**Comment by Mic92** [comment]
I don't think it fixes the issue reported here because it checks the presents of both files: https://github.com/nix-community/nix-direnv/blob/363835438f1291d0849d4645840e84044f3c9c15/direnvrc#L268

**Comment by bbenne10** [comment]
You are, of course, correct. I had classified this as a problem of tracking too loosely, not tracking aggressively.

The issue here is that our file watching is always going to be heuristic. 
If we watch too many files, we get this issue (and other similar ones).
If we watch too few, the burden on the consumer is too high.

There're a couple solutions for this, but I'm not sure that I like them much:

* untrack `default.nix` from `nix_watches` (`use_nix` will only track `shell.nix`)
* untrack `shell.nix` from `nix_watches` (this is obviously wrong, but `use_nix` would only track `default.nix`)
* Track *neither* and require the users to add watches for each of the files they want watched.
* Require the user to provide the entry point when calling `use_nix` (This is more explicit and would simply add one or the other of `shell.nix` or `default.nix` to `nix_watches`. This is also backwards incompatible in a naive implementation)

Any of these require a bump in version imo, as they aren't "bug fixes" as such - they're changing the way watches work fundamentally. The last might qualify for a major bump though (the rest are probably minor or bugfix bumps?)

@Mic92: Thoughts? I can probably work up a PR at some point for whatever we decide.

**Comment by Mic92** [comment]
@bbenne10 I increased the bus factor of the project by also inviting you to the project as a maintainer.

**Comment by Mic92** [comment]
Don't hesitate to merge PRs and make releases as you find it reasonable to do.

**Comment by bbenne10** [comment]
I'm more inclined to watch fewer files by default because we can append to `nix_watches` via user configuration but cannot unwatch a file in the same way. My preferred approach here would be to make a backwards-incompatible change and simply *require* an entry point for both `use flake` and `use nix` (`use nix` would take a file path and `use flake` would take a flake specifier)

Then we would only watch the following:

* `$HOME/.direnvrc` (as an aside: why do we track this? `direnv` lists`${XDG_CONFIG_HOME:-$HOME/.config}/direnv/direnvrc` as its config file?)
* `.envrc`
* `.env`

You'll also note that I'm also inclined to make `devshell.toml` watching opt-in.

Users can expand this (and maybe we can wrap some common scenarios up in a function: `nix_direnv_watch_all_nix_files`, `nix_direnv_watch_devshell` etc.)

**Comment by polygon** [comment]
Changing the default watches might break a lot of existing deployments. The breakage will also not happen loudly if we just remove the default watches. Instead, it will happen silently by not updating a cached environment when it used to update before. 

I believe that the default watches are very sensible and strike a good balance between preventing unnecessary evaluations and "just working" for the majority of use-cases.

I do see the need for customization here. But to prevent breakage, I suggest that we instead check some environment variable that can be used to disable adding default watches. For example, we could check `NIX_DIRENV_NO_DEFAULT_WATCHES` and when it is set, we do not add any of the default watches. Users can then use `nix_direnv_watch_file` to manage the watch list themselves.

**Comment by bbenne10** [comment]
This is the point of using semver. Breaking changes are introduced only at major releases. Users are warned of breaking changes and can choose to stay on old revisions until ready to update. 

I think that a real problem here is that direnv ships integration with nix-direnv as part of its direnv integration and it is unclear what version of nix-direnv you're getting if you use this integration. This has been problematic for me in the past, so I just use the flake shipped as part of this repo in my `programs.direnv` block (assuming the input is called `nix-direnv`):

```
    programs.direnv = {
      enable = true;
      enableZshIntegration = true;
      nix-direnv = { enable = false; };
      stdlib = ''
        source ${nix-direnv}/direnvrc
      '';
    }; 
```

I've attempted to strike some balance between the two extremes in my fork (which I'm using to test nix 2.4+ features primarily, but some of this leaked in there too). 

The idea there (on the `nix24` branch) is that the files are only tracked if they exist on disk, but this doesn't help in this particular scenario. 

I want to enforce that every usage of `use flake` or `use nix` requires an entrypoint and that entrypoint file would be the only file tracked (in addition to a very conservative set of files tracked by default), but I haven't gotten around to that yet.

**Comment by bbenne10** [comment]
I honestly don't know that there's anything that we can do short of changing the way we watch files pretty extensively. To that end, I am closing this as `wontfix`. I'm sorry for the delay in a decision here, but this is simply a fallout of how we watch files. The caching we provide should at least make it quite a quick noop.
