### ISSUE TITLE
custom nix filename does not work

### ISSUE THREAD

**Issue by gador** [nix-community/nix-direnv#162]
When not using `default.nix`or `shell.nix` but a custom filename in my `.envrc` I get the error:
```
error: opening file '/home/user/software/git/project/default.nix': No such file or directory
```
my `.envrc`:

```
use nix direnv.nix
```

When I prefix the file with `-` it works (assuming the file is also prefixed).
I assume it has something to do with this:
https://github.com/nix-community/nix-direnv/blob/f8ae7be11f87c168cede1049bf48026bf83b2dbf/direnvrc#L287-L293

It doesn't work as an catch-all, but only catches `-`

I assume it has to do with the re-work for nix-2.4 options in https://github.com/nix-community/nix-direnv/commit/3cca1afdec33bc2b860794718c7e2db0c94c168c

**Comment by bbenne10** [comment]
I have just merged the fix for this, but we have yet to pin a new release for it. I'm opening a ticket to discuss how we might handle that better, but I think we'll need to use the old process to get this fix in a release first. In the meantime, you can grab `master` to get the fix (and can do so with the process documented in the README). If you notice a problem with the solution I have merged, please open a new ticket. Thank you for bringing this up!

**Comment by gador** [comment]
awesome, thanks for the quick fix!
Works just fine on my end :+1:
