### ISSUE TITLE
nix_direnv_watch_file: command not found

### ISSUE THREAD

**Issue by jsierles** [nix-community/nix-direnv#169]
Following the docs, I added this to my `.envrc`:

```
use nix
nix_direnv_watch_file gemset.nix
```

Leading to the error `nix_direnv_watch_file: command not found`. What might be happening here?

**Comment by Mic92** [comment]
Make sure you have a least nix-direnv 1.6.1, where this function was introduced: https://github.com/nix-community/nix-direnv/commit/1241f1115ed56a6b3cb9ba14418231d14467d9f1

**Comment by jsierles** [comment]
I'm running `nix-direnv 2.0.0`:

```
nix-env -iA nixpkgs.nix-direnv
replacing old 'nix-direnv-2.0.0'
installing 'nix-direnv-2.0.0'
$ cd myapp
direnv: loading ~/myapp/.envrc
./.envrc:1: nix_direnv_watch_file: command not found
direnv: using nix
```

**Comment by bbenne10** [comment]
Is it pos

**Comment by bbenne10** [comment]
Can you please upload the content of your nix-backed `direnvrc` and post a link here? I'd like to inspect it to see if it is, in fact, 2.0.0. 

Are you *sure* you're not getting `nix-direnv` from somewhere else? Home-manager can integrate `nix-direnv` into `direnv` for you, for instance, which can lead to some confusion on what version you're actually using.

A debugging step that will tell you if your `.envrc` is sourced with a proper version of `nix-direnv` is to add the following to the head of your `.envrc`:

```bash
if ! has nix_direnv_version; then
  echo "No nix_direnv at all!"
  exit 1
fi

if ! nix_direnv_version "2.0.0"; then
  # This already prints a message if the required version is missing
  exit 1
fi
```

This should tell you what version it is executing with and fail if < 2.0.0.

**Comment by jsierles** [comment]
I get `No nix_direnv at all!`

My `~/.direnvrc` contains:

```
source $HOME/.nix-profile/share/nix-direnv/direnvrc
```

That file exists, and points to:

```
$ ls -lsa ~/.nix-profile/share/nix-direnv
0 lrwxr-xr-x  1 root  wheel  77 Jan  1  1970 /Users/me/nix-profile/share/nix-direnv -> /nix/store/5dm2lamckss4y0zqvk0rgiarl7kx4802-nix-direnv-2.0.0/share/nix-direnv
```

**Comment by bbenne10** [comment]
This looks a lot like you've simply *installed* nix-direnv and have not *sourced it*.
Because `direnv` itself includes a `use nix`, this can be confusing.

Merely installing with `nix-env` is not sufficient.
You'll need to **source** the provided direnvrc.

Please see the README for installation instructions.
This section should work: https://github.com/nix-community/nix-direnv#with-nix-env
(I say "should" because there's other things that could invalidate your current profile that I cannot predict)

I wholeheartedly recommend either home-manager or direct integration into your configuration.nix over this approach.

If you continue to have problems, please respond with the contents of:

* `$HOME/.direnvrc`
* `$HOME/.config/direnv/direnvrc` (this may not exist - that's fine. Just mention that)
* The project's `.envrc`
* The project's `.env` (this may not exist as well. Just mention that fact)

**Comment by jsierles** [comment]
Thanks - I found the issue! I had both `~/.direnvrc` and `~/.config/direnv/direnvrc`. The latter was taking precedence. Moving the source to that file fixed things.

I'm not using home-manager or configuration.nix to keep instructions simple for others on the team.

**Comment by bbenne10** [comment]
Oh! If you're intending to check this in, I might recommend the approach we're taking: Source it INSIDE the local project's `.envrc`.

You can do so with https://github.com/nix-community/nix-direnv#direnv-source_url, but make sure it is added before the `use nix` line. 

Glad you got it sorted out :)

**Comment by zmrocze** [comment]
Hey, just letting know that you'll hit this error (as I did) when missing 
```
programs.nix.nix-direnv.enable = true;
``` 
from homemanager config.
