### ISSUE TITLE
Create gcroot link directly in /nix

### ISSUE THREAD

**Issue by peterhoeg** [nix-community/nix-direnv#224]
today the way things work is as follows with gcroots assuming a user named "peter":

1. `/nix/var/nix/gcroots/per-user/peter/some_long_name-flake-profile-some_hash` -> `/home/peter/.cache/direnv/layouts/some_dir`
2. `/home/peter/.cache/direnv/layouts/some_dir/flake-profile-some_hash` -> `/nix/store/some_hash-nix-shell-env`

The problem with this approach as mentioned in #218 is that in case `/home` isn't available when garbage collection runs, which is entirely possible if `/home` is on an encrypted and still locked volume, the first link is deleted (it's stale) and subsequently `/nix/store` has the nix-shell-env removed because there is nothing linking to it.

There is of course nothing wrong with the 2 links mentioned, but we probably should also create a link that doesn't require `/home` to be available:

`/nix/var/nix/gcroots/per-user/peter/direnv/some_long_name-flake-profile-some_hash` -> `/nix/store/some_hash-nix-shell-env`

`nixops` creates links in a subdirectory, so maybe we do the same here?

**Comment by peterhoeg** [comment]
ref: https://github.com/zhaofengli/colmena/issues/118

**Comment by bbenne10** [comment]
Out of curiousity - could you use https://github.com/direnv/direnv/wiki/Customizing-cache-location to centralize the cache dir outside of `$HOME` and get the same benefits? Maybe only if the folder in question contains some `*.nix` file so that the non-nix projects don't necessarily end up in that spot (assuming that's not desirable).

**Comment by peterhoeg** [comment]
Well, technically yes, but that’s a really ugly workaround. 

Assuming there is no interest in doing this in nix-direnv, my own preferred workaround is a job that runs once a day and auto-creates the symlinks directly. 

I guess the question to ask is why wouldn’t you want nix-direnv to do this? Would you take a PR that implements it?

**Comment by bbenne10** [comment]
Overall, a direct implementation of this feature would be pretty simple: You'd simply modify `_nix_add_gcroot` to create a new dir under `/nix/var/nix/profiles/per-user/$USER/nix-direnv` or something and create a canonical symlink from the store path there using the same methods we have now and then symlink from `/nix/var/nix/profiles/per-user/$USER/nix-direnv` to `/home/$USER/.cache/direnv/...`

But this ignores a wider view: We now have two canonical symlinks pointing into the store and figuring out how to actually garbage collect the nix-direnv roots is now non-obvious (from a nix-direnv user's perspective).
You cannot simply delete the symlink (or clear out your direnv store) because there's still another symlink that points into the store and keeps the root alive. 

I truly believe that the root problem here is that the **transient** failure to resolve a symlink is causing garbage collection to run against a valid gcroot. The fix for this is to have automatic garbage-collection wait until all mount points have been mounted before continuing rather than to have piecemeal solutions in other tools. The fact that other tools have adopted the piecemeal solution is of little value meaning here. We should not be running garbage collection with partial information.

@Mic92 may have a different view on this and I'll defer to any decision they may make, but without convincing I think that I am a "no" on this feature. If there is a way to implement it cleanly without additional messy argument handling in direnv, I may be persuaded otherwise from other arguments though.

**Comment by Mic92** [comment]
So does your home gets unlocked when you log in? Otherwise you can configure your nix-gc service to have `RequiresMountsFor=/home` set.

**Comment by peterhoeg** [comment]
> I truly believe that the root problem here is that the transient failure to resolve a symlink is causing garbage collection to run against a valid gcroot.

It’s one way to look at it, *but* what it really comes down to is direct vs in-direct gcroots. And while you are right that doing *both* at the same time does create a whole new set of issues that go against the “principle of least surprise’, the real question is if nix-direnv should just do direct gcroots instead of the current in-direct.

> The fix for this is to have automatic garbage-collection wait until all mount points have been mounted before continuing rather than to have piecemeal solutions in other tools.

The problem with this is that you will never know when all mount points are there.

> The fact that other tools have adopted the piecemeal solution is of little value meaning here.

They haven’t though. nixops just creates direct gcroots. That’s not in any way the wrong solution.

The issue with nix-direnv doing direct gcroot is the fact that the .direnv directory (either project-specific or centralized) is used *both* for gcroots and for other state data. As an example, `layout ruby' makes all the gems go there too.

So if you are saying “we want everything that belongs to this environment to be in one place regardless of what it is”, then we don’t really have any other way to approach it than indirect links.

> (I was previously unaware of colmena. Thanks for the share!)

It’s wonderful after having had to deal with nixops state files!

> So does your home gets decrypted when you log in?

It does, yes, but I happen to know that I need this thing mounted, but that’s really still a workaround.

> delete the project the gcroot is removed as well. I find this property more important for most users than the edge case you describe.

And that’s absolutely fair enough. As it is now, I need to work around this anyway and the 8 line bash script that creates the direct links once a day isn’t an issue. For me it’s more important *not* to lose the environments rather having to blow away two sets of links.

**Comment by bbenne10** [comment]
> The problem with this is that you will never know when all mount points are there.

This is, of course, a true statement. There's no way for the system to know at any point if there are additional mounts it does not know about containing symlinks in to `/nix/store`. But it ignores the fact that the user could say "I have mounts for all of these places and you need to wait for them all" (or "I have mounts for all of these places but I only want you to wait for these few.").

Currently `nix.gc.automatic` can only run on a timer and doesn't allow setting `RequiresMountsFor`.
Regardless of the discussion of direct vs indirect links, adding support for requiring a set of mounts for automatic garbage collection feels more correct to me than piecemealing a solution together.

If the garbage collector only runs when the whole system is up-and-mounted, there's no *need* for any tool to worry about where it puts any of the symlinks at all. Only that they write one (and only one) symlink that their users can easily find.

**Comment by bbenne10** [comment]
(Further, I think you could easily create `my-nix-gc` that does exactly what we're discussing without modifying the `nix-gc` nixos configuration by cloning the behavior [here](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/misc/nix-gc.nix#L89), if I understand the `systemd.services` correctly)

**Comment by peterhoeg** [comment]
> But it ignores the fact that the user could say "I have mounts for all of these places and you need to wait for them all"

Sure, but then we're back in workaround-territory.

`nix-direnv` could work without workarounds, but that requires direct gcroots (replacing, not in addition to indirect gcroots) and of course that goes aginst the "everything in a single directory" requirement. 

Time for a management decision! ;-)

**Comment by bbenne10** [comment]
It is all a matter of perspective.

You, the manager of a machine, need to make a decision about when garbage collection runs and what mountpoints exist on that machine.
nix-direnv already creates gcroots for environments it creates and has no line of sight on whether or not the mounting of stuff has completed (nor does it care).

direct gcroot creation works around this problem by creating a gcroot in a place that happens to be mounted already.

Changing the auto-gc systemd service by adding `RequiresMountsFor` works around the problem by adding a static list of mount points to wait on (rather than doing mount point discovery and waiting for any and all possible ones).

I'm going to close this. We won't be fixing it as we believe a fix should be applied either to the upstream auto-gc systemd job (by waiting for all declared mountpoints to be ready) *or* by customizing the gc systemd job to do so without needing to patch the upstream one. The mainstream appeal of handling all direnv related cleanup in a single spot outweighs the corner case you present and the cost-benefit of modifying our argument handling to deal with swapping the behavior. Thanks for opening the issue. I'm sorry the resolution isn't better.

**Comment by peterhoeg** [comment]
Well, technically yes, but that’s a really ugly workaround.

Assuming there is no interest in doing this in nix-direnv, my own preferred workaround is a job that runs once a day and auto-creates the symlinks directly.

I guess the question to ask is why wouldn’t you want nix-direnv to do this? Would you take a PR that implements it?

**Comment by peterhoeg** [comment]
I'm sorry about bringing this back to life. It looks like I initially replied back in August via email to github but it's only *now* adding it as a comment and thus necro-bumping the issue.
