### ISSUE TITLE
`shellHook` is executed, but `alias` and functions are lost

### ISSUE THREAD

**Issue by edio** [nix-community/nix-direnv#245]
I use nix-direnv together with flakes (`use flake`)

My `flake.nix` contains a `devShell` output with a non-empty `shellHook`. Any aliases, exported variables or custom functions I may define in the `shellHook` won't be sourced to the current shell.

`flake.nix` to reproduce
```
{
  inputs.nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
  inputs.flake-utils.url = "github:numtide/flake-utils";
  outputs = { nixpkgs, flake-utils, ... }: flake-utils.lib.eachDefaultSystem (system:
    let
      pkgs = import nixpkgs { inherit system; };
    in rec {
      devShell = pkgs.mkShell {
        shellHook = ''
          echo "This is executed"
          export VAR_FOO="This is set"

          function f_foo {
            echo "This is lost"
          }
          alias a_foo="true"
          '';
      };
    }
  );
}
```

`use flake` in the `.envrc`, `direnv allow` to enable devShell.

In the shell
- observe the line `This is executed`
- echo `$VAR_FOO`, observe `This is set`
- try calling `f_foo` (should fail)
- try calling `a_foo` (should fail)

I'd expect aliases and functions to be propagated to the current shell to be consistent with exported variables and other side-effects

**Comment by Mic92** [comment]
This is a limitation of direnv itself. Direnv does not support aliases and functions. Only environment variables can be imported

**Comment by bbenne10** [comment]
@Mic92 is right, but I think a bit of clarification is in order:

direnv launches the entirety of it's shell processing in a standalone bash shell, no matter what your user shell is.
It then runs through the entire process of resolving the environment from beginning to end in this standalone shell.
It notes the environment variables as they are at the start of the shell and then again at the end of the shell invocation.
The difference between the start and end environment is what is exported to the user's shell after the fact.

The problem with this, as you've noticed, is that aliases and functions are lost because they're not environment variables.
Some thought about this problem will reveal that it isn't REALLY possible to fix the function problem (even if it is possible to fix the alias problem). Functions have arbitrary bodies that do arbitrary things. direnv is available for a number of incompatible shells and cannot possibly translate your bash function body for consumption in, say, an elvish user's shell session. This may not be important for you - I genuinely don't know your use case - but it is something that direnv itself has to take into account.

**Comment by abhillman** [comment]
This is a workaround I wrote to get around `alias`es declared in `shellHook` not being preserved:

```

      shellHook = ''
          # This is a hack to get around `alias` not working with direnv/nix
          export DIR=$(mktemp --directory --tmpdir=/tmp)
          export PATH="$DIR:$PATH"
          echo "nvim" > $DIR/vim
          chmod +x $DIR/vim
      '';
```

**Comment by bbenne10** [comment]
Another (maybe more nix-ish) solution would be to use `writeShellScriptBint` to build a derivation for the functions/aliases you want and then add them to the environment itself. IMO `shellHook` is *rarely* the right solution (unless you're doing something that only prints to the terminal or something)

**Comment by musjj** [comment]
Using wrapper derivations can work, but the nice thing about aliases is that they're easy to override. You can just run `command ...` and now you have access to the original program. You lose this benefit when using wrappers.

**Comment by bbenne10** [comment]
I agree that aliases are convenient, but the fact remains that they are *shell dependent*. Direnv - a tool we explicitly depend on for nix-direnv - cannot support them because it strives to be shell independent (by using bash internally and mapping over the variable export behavior shell-by-shell). Until direnv supports aliases, we are stuck. 

Are there hacky obscure things we could do? Yeah - probably. They will likely cause more trouble than the feature is worth, in my opinion.

If you want aliases without direnv support, fork. I personally will not be merging anything less than 100% tested and upstream supported alias support. 

I do not mean to be hostile here, but rather to be clear. We will not support aliases or shell functions until there is a supported and clear path forward from our upstream (and direnv is explicit about this limitation, so I do not expect it to be changing any time soon)
