### ISSUE TITLE
Consider informing about out of date nix-direnv only when major and minor versions are too old

### ISSUE THREAD

**Issue by jozuas** [nix-community/nix-direnv#259]
```sh
if [[ ($req_major -gt $major) \
     || ($req_major -eq $major && $req_minor -gt $minor) \
     || ($req_major -eq $major && $req_minor -eq $minor && $req_patch -gt $patch)
  ]]; then
    printf '%s\n' "nix-direnv: error current version v$major.$minor.$patch is older than the desired version v$1" >&2
    return 1
  fi
```

Maybe `|| ($req_major -eq $major && $req_minor -eq $minor && $req_patch -gt $patch)` is a bit too strict?

I would personally like not seeing `nix-direnv: error current version v2.1.0 is older than the desired version v2.1.1` when I'm out of sync by one patch version.

**Comment by Mic92** [comment]
You can just pass `nix_direnv_version 2.1.0` instead of `nix_direnv_version 2.1.1` if you want a different minimum version to be checked:

Here an example:

```
if ! has nix_direnv_version || ! nix_direnv_version 2.1.0; then
  source_url "https://raw.githubusercontent.com/nix-community/nix-direnv/2.2.0/direnvrc" "sha256-5EwyKnkJNQeXrRkYbwwRBcXbibosCJqyIUuz9Xq+LRc="
fi
```

**Comment by bbenne10** [comment]
Frankly, I think I fundamentally disagree with you here.

If I have specified that I require `1.2.3` as the minimum required version - there must be some REASON I have specified patch level 3 as required. Otherwise - I would've specified `1.2.0`. SemVer means nothing in the face of real world problems, I think. Especially when I see stuff like Python (a huge proponent of SemVer) making minor releases that should be major.

If you want to relax the version you are using - relax the patch version you are using to `x.y.0`. I am not relaxing the correctness of this function. Closing.
