### ISSUE TITLE
`use flake` does not entirely load the shell on M1 Mac

### ISSUE THREAD

**Issue by davesmith00000** [nix-community/nix-direnv#288]
Thanks for building this - it's a great project!

I have a Linux machine, an intel Mac, and an M1 mac I use regularly. On Linux and Intel Mac, a `.envrc` file that just contains `use flake`, works perfectly.

On the M1 mac, it runs the shellHook and appears to be loading things, but in fact ultimately leaves you at your normal shell. For example, I use flakes to manage the JDK version on a project by project basis, and instead of changing to version 11 (as it does correctly if I run `nix develop`), I remain on version 19.

I did also try replicating your flake template but that made no difference.

I wondered if you'd heard of this and knew of any workarounds?

**Comment by bbenne10** [comment]
Whenever we see a problem like this, we typically find that the user's shell configuration is set up improperly or there's some assumption of functionality that is not present. If you'll please make sure that you've set up direnv, nix-direnv, and your flake properly first and - if that doesn't resolve the issue - please post the shell initialization files/snippets you're using and the flake you're having trouble with, we should be able to sort this out. I've tested nix-direnv extensively on an intel mac, and I don't think the difference in architecture should make a lick of difference here.

**Comment by davesmith00000** [comment]
Hi - thanks for getting back to me. I'm going to close this because upon investigation, you're quite right! (Also the M1 bit was a red herring.)

However if you have any suggestions or advice I'd be pleased to hear it (no pressure though).

So I downloaded the template from the repo (directly this time, made no assumptions) and it worked perfectly with my nix-direnv via home manager installation. I then gradually moved the flake that didn't work into the working example until it broke, one small change at a time.

Turned out to be the `shellHook`, and I guess this sort of thing just might not work at all with direnv or even be appropriate - but it works fine in a normal Flake. The two things that break it are:

1. The shell hook starts `socat` as a background process to redirect some network traffic. With this line in place, the shell never completes because the process blocks. It's like any attempt to run the process in the background is being ignored.
2. I also had a little `trap` line (interestingly, point (1) can be in place or not here, makes no difference) so that when the Flake exit's I can kill the background process. With that line in place, it never gets called, but the nix flake simply doesn't load at all - actually not quite true - this is the behaviour I originally reported: It looks like it's doing stuff but actually silently fails and bombs out.

As I said, I now suspect you just can't / shouldn't be doing this with direnv at all - does that sound right? For one thing you need to start adding checks and logic to decide if the little bacjground process has started or should be killed on exit or if another shell is still using it etc.

That being the case, my plan B (as yet, not attempted), is to use devshells so that I have one devshell which is the `direnv` one and it just does straight forward package and environment management, and another devshell that you enter manually (without direnv) to do all the fancier stuff. Does that sound reasonable? Do you know of any other approaches to this sort of thing?

**Comment by bbenne10** [comment]
The reason you're having problems is because of the way shellHook interacts with {nix-,}direnv. 
It is worth noting here that direnv spawns a subshell, invokes the environment handler, and then extracts environment variables from that subshell. The shell that direnv  runs is not the one you are interactively using.

This causes all sorts of oddities when users expect `shellHook` to directly modify the interactive shell (as you saw).
You can, for instance, export variables in `shellHook` but any job control is off the table due to the problems you noticed. I am not 100% certain, but I suspect that direnv expects the shell to exit normally and kills the subshell after a bit.

Either `nix develop` or `nix run .#<theThing>` is probably more along the lines of what you want. `nix develop` because it spawns its own bash instance (and doesn't need to take into account zsh/fish/elvish etc like direnv does). `nix run` because it is explicit and can be tailored to your use case better.
