### ISSUE TITLE
Pass on nix error messages

### ISSUE THREAD

**Issue by pinselimo** [nix-community/nix-direnv#305]
I just ran into ``nix-direnv`` failing with: "direnv: nix-direnv: nix version is older than the required 2.4."
I am running nix 2.13.2 and the issue was caused by the nix store running out of space.
This was reported by ``nix-shell`` but ignored by ``nix-direnv`` in its error reporting.

Wouldn't it be better to report the error message given by ``nix-shell`` in the check and amend it with something along the lines of "Maybe your nix version is older than the required 2.4" ?

**Comment by bbenne10** [comment]
Yes - this would be a better behavior. As of now, we're invoking `nix` with options we know only exist on new enough versions and it fails because this is the first invocation of nix in the script and we just so happen to also redirect stderr here. 

I think we should instead use `nix --version` and parse the return string to get the current version, letting stderr bubble there. I'm not sure if it will fail there, but it should soon afterwards.

I probably won't have time to handle this soon, but a PR is welcome.
