### ISSUE TITLE
Flakes: nix develop instead of nix shell

### ISSUE THREAD

**Issue by ostrolucky** [nix-community/nix-direnv#324]
What I would like to execute upon cd to directory is `nix develop --impure`. However, what this tool seem to be doing is `nix shell --impure` (after doing `echo "use flake . --impure" > .envrc`)

**Comment by bbenne10** [comment]
It is not doing either of those things. We actually run (in your example)`nix print-dev-env --impure`. How are you distinguishing between the `nix shell` and `nix develop` cases?

**Comment by ostrolucky** [comment]
I use zsh on host system. Running nix develop enters bash shell which makes it obvious it's not zsh, command prompt is completely different there.

<img width="384" alt="image" src="https://user-images.githubusercontent.com/496233/228637383-8554041d-608c-43ea-88c2-1fe1e0853f5a.png">

I expect nix develop because unlike nix shell, pkgs.mkShell supports shellHook option where I can execute arbitrary commands when entering shell.

**Comment by bbenne10** [comment]
I'm afraid you'll be a bit disappointed then. The whole point of nix-direnv is to integrate with your host shell. `shellHook` is an interesting case: It is executed, but is executed inside the shell that direnv spawns rather than your host shell - meaning that the utility is pretty limited overall (you can spawn background jobs if you need to but you must persist their pid somehow and then disown them before the shell exits, for instance). 

It is worth noting again that we do not run either `nix shell` or `nix develop` directly. Rather, we execute `nix print-dev-env`, which effectively gives you the nix develop shell script and pass that into direnv, which then manages setting (and eventually unsetting) the environment variables for us. aliases and the like are unfortunately impossible to handle using nix-direnv alone. This is not possible for us to change, as this is core to how direnv works. If you want auto-invocation of `nix develop` when a `flake.nix` is present, I might suggest looking into the `chpwd_functions` array.

**Comment by ostrolucky** [comment]
Alright, thanks for looking into this

**Comment by ostrolucky** [comment]
Here is a simple solution for chpwd_functions, which can serve as an alternative to direnv (thx for suggestion!) and works good in my case:
home.nix:
```nix
{
  programs = {
    zsh = {
      enable = true;
      initExtra = ''
        # direnv alternative that plays nicely with nix develop
        # see https://github.com/nix-community/nix-direnv/issues/324
        # see https://github.com/direnv/direnv/issues/1084
        function enterNixDevelopShell {
          if test -f flake.nix; then nix develop . --impure; fi
        }
        chpwd_functions=(''${chpwd_functions[@]} "enterNixDevelopShell")
    };
  };
  programs.home-manager.enable = true;
}
```

Of course it's quite barebones at the moment and might not fit all usecases, use as a base.

**Comment by bbenne10** [comment]
Glad you got what you needed!
