### ISSUE TITLE
Workaround NixOS/nix#3121 by vendoring flake

### ISSUE THREAD

**Issue by j-baker** [nix-community/nix-direnv#347]
I have a dev environment for a large project. It's a 3d game, and contains gigabytes of assets. Each time a flake computation occurs, due to https://github.com/NixOS/nix/issues/3121 the flake evaluation takes forever because the whole directory is copied into the store.

For purposes of direnv, this is basically the opposite of what you want - you want to evaluate your dev-shell, and it shouldn't really depend on random files you have in your repo. Your nix build, certainly.

I worked around this for myself by creating an .envrc like

```
SHA=$(cat flake/** | sha256sum | cut -d' ' -f 1)
CACHE_PATH=~/.sparseflake/$SHA
if [ ! -d $CACHE_PATH ]; then
  mkdir -p $CACHE_PATH
  cp -r flake $CACHE_PATH
fi
use flake $CACHE_PATH/flake
```

This approach totally solves my problem, as by vendoring the flake, the rest of the tree is no longer copied.

I'd love nix-direnv to perform this optimisation automagically on behalf of the user.

I accidentally filed this here as well: https://github.com/direnv/direnv/issues/1103 since it's late in the day for me - I felt it was more likely to receive attention here.

I obviously can solve this myself. I figured it might be helpful for others for nix-direnv to work around on behalf of the use given its focus on speed.

**Comment by bbenne10** [comment]
@Mic92 has stated that full caching is a feature rather than a bug, but this was in reference to the full cache of flakes and their inputs (so remote artifacts). I'm not sure what that means in relation to this particular issue.

However, I'm not sure I think that we can necessarily safely do what you're suggesting blindly. What if the devShell depends on local derivations? Copying the flake by itself is not going to work, and then you're basically in the same scenario you're in right now - whitelist the things you need to have to get the devShell working properly and manually copy them into the subdir.  I am not aware of a solution for this shortcoming (as we don't have tracing of imports in nix-direnv). If we are to implement something like this - it would absolutely need to be opt-in rather than opt-out, as the change in behavior is not always safe. 

Additionally, I'm curious how your implementation works long term. It seems to me that it is going to leave a bunch of active gcroots around, since the caching happens pre-nix-direnv and we can't then clean up after ourselves.

I'm not saying that this is a *bad* idea - but that I don't know yet how to do it generally. If we can figure out either how to safely opt-in or how to trace nix imports (with maybe then having to do import rewriting...maybe this is not a good path...), I'd accept a PR for it.

**Comment by Mic92** [comment]
I think the simplest solution to your problem would be to have your flake in a subdirectory   to avoid copying the whole repository. You can can even use nix-store --add on this directory and use the resulting store path as a cache key for evaluation. I think devenv also has some optimizations for large repositories if I remember correctly (@domenkozar). For now I want to keep the semantics of use_nix / use_flake compatible with the direnv stdlib. That being said I could imagine having other helper functions that add on top of that.

**Comment by j-baker** [comment]
Thanks for the detailed comments, they help me understand where my workaround falls short! My understanding wrt the upstream issue is approximately:

- It's widely known as making it harder to use in-tree flakes (IMO, in-tree flakes are sort of what nix-direnv is meant for). It's harder because it can be super slow, and there are many folks who've complained about this.
- The Nix-side solution appears to be to provide a 'virtual filesystem' to Nix, where the required files are accessed through an abstraction layer which can copy them lazily (and sometimes, not even copy). This is here https://github.com/NixOS/nix/pull/6530. It's a complex PR, which unfortunately recently mourned its first birthday.

Regarding the dev-shell depending on local derivations (here I assume we mean derivations that rely on files in the directory, rather than e.g. something which downloads a file) - obviously my solution doesn't work at all with regards to this, the two are essentially incompatible. I don't think this is necessarily incompatible with nix-direnv - for example, the functionality could be enabled based on the absence of `nix_direnv_watch_file` calls, or alternatively enabled based on some other function (e.g. `nix_direnv_build_out_of_tree`).

Regarding the GC issue, I've read the nix-direnv code a little more deeply. It's very possible I've grossly misread - my bash reading skills are rudimentary at best. However, what I'm seeing is something where the problem can be easily avoided if implemented against at the nix-direnv level. In particular, the cache key used for the profile is the argsum of the input arguments. This means that if nix-direnv did the copy to a temporary directory pre-evaluation, the gcroots would not be duplicated.

What do you think?

**Comment by j-baker** [comment]
For why this behaviour occurs, I believe it's because...

Here:
https://github.com/NixOS/nix/blob/f41dd2c306a5986340b04c1635bd674e4a01b78d/src/nix/flake.cc#L769

the Flake discovery code in Nix looks for the git root of any flake passed in, even though the build won't then use it. I'll have a go at PR-ing Nix here.

**Comment by j-baker** [comment]
My hope is that something a bit like https://github.com/NixOS/nix/compare/master...j-baker:nix:jbaker/dont_redundantly_copy?expand=1 will fix this problem on the Nix side. However, I cannot get the tests to work right now (exit 1 does not fail the build), so I don't know if my change works at all. However, that might be a more appropriate solution to this problem!

**Comment by bbenne10** [comment]
> Regarding the dev-shell depending on local derivations (here I assume we mean derivations that rely on files in the directory, rather than e.g. something which downloads a file) 

This is a correct understanding and is a huge shortcoming of the solution you propose, in my humble opinion. The shortcoming can be worked around at the cost of some complexity in nix-direnv's code, however.

>  `nix_direnv_build_out_of_tree`

If you are proposing breaking api compatibility with the upstream direnv by introducing new entry points, I think that is a non-starter. In fact, it might be a good place to offer another fork (and you could pretty easily simplify, by not offering legacy `use nix` support at all).
 
> However, what I'm seeing is something where the problem can be easily avoided if implemented against at the nix-direnv level. In particular, the cache key used for the profile is the argsum of the input arguments. This means that if nix-direnv did the copy to a temporary directory pre-evaluation, the gcroots would not be duplicated.

This is exactly correct. It could be fixed in nix-direnv, but to be frank: I have little motivation or time to fix it right now - my personal life is quite busy at the moment. Should someone come up with a PR for this functionality, I would happily review it and set it on the path to merging (or merge immediately if it was a good fit up front). I could see a path that either 1) added a new argument to the existing `use flake` workflow that opted into this behavior or 2) uses the heuristic you mentioned about having never called `nix_direnv_watch_file`. There are a few things to watch out for though: Firstly, when changing the invocation arguments in the first case (or subsequently calling `nix_direnv_watch_file`), we would have to check *both* possible locations for the flake and its cache directory in order to clear it. Secondly, the heuristic may occasionally get stuck for one reason or another (A flake that is built with no calls to `nix_direnv_watch_file`, but *does* have local dependencies, for instance) - and we must handle this scenario gracefully.

**Comment by Mic92** [comment]
@j-baker how did you add the flake?
What should work is doing `use flake path:some/dir` because otherwise it will try to copy in the whole git repository again.

**Comment by j-baker** [comment]
Hi @Mic92. That definitely seems promising. It does however expose a bug in nix-direnv:

```bash
  flake_expr="${1:-.}"
  flake_dir="${flake_expr%#*}"

  local files_to_watch
  files_to_watch=(".envrc" "$HOME/.direnvrc" "$HOME/.config/direnv/direnvrc")

  if [[ -d "$flake_dir" ]]; then
    files_to_watch+=("$flake_dir/flake.nix" "$flake_dir/flake.lock" "$flake_dir/devshell.toml")
  fi
```

as this logic cannot handle prepending `path:`, and responds by not properly caching any changes to the flake. I've resolved by having my .envrc read as:

```
nix_direnv_watch_file flake/flake.nix
nix_direnv_watch_file flake/flake.lock
use flake path:flake
```

Having said that, yes, that worked! Thanks for the help!

**Comment by bbenne10** [comment]
I'd happily merge a PR that works around the `path:` prefix bug (likely with `flake_dir=${flakedir#"path:"}` and an accompanying in-line comment).

**Comment by hedefalk** [comment]
Just moved a project from `use nix` to `use flake` and it started taking _forever_. My use case is just that I want a dev env setup, nothing dependent on the tree itself. 

```
nix_direnv_watch_file flake/flake.nix
nix_direnv_watch_file flake/flake.lock
use flake path:flake
```

made my day. Thanks! @j-baker
