### ISSUE TITLE
Issue when .envrc points to a flake in a git repository

### ISSUE THREAD

**Issue by realbogart** [nix-community/nix-direnv#480]
Hi,

Today I ran into an issue where I have the following in my `.envrc` file:
`use flake git+ssh://git@gitlab.my-selfhosted-gitlab/test.git`

It works well but gets stuck on one commit. If I make a change to my `test.git` repository and push it, the new environment is never picked up. I have tried manually deleting the `.direnv` directory. Any ideas on how to resolve this?

Thank you!

**Comment by realbogart** [comment]
I managed to make it update by changing `.envrc` to:
`use flake git+ssh://git@gitlab.build.paradox-interactive.com/gsg/tech/conan/conan-nix.git --refresh`

I'm not sure if this is the correct solution though.

**Comment by bbenne10** [comment]
"gets stuck on one commit" isn't exactly clear. What does that mean exactly? Is the URL in your reply the one we can use to reproduce this problem (without `--refresh`)?

**Comment by bbenne10** [comment]
Oh. Yes - this is expected behavior. The git hash is resolved when the cache is created. (There might be more nix caching going on behind the scenes too, actually. I'm not entirely sure and have not gone poking around).

I think that `--refresh` is probably the best way to handle this with `nix-direnv`.

**Comment by realbogart** [comment]
Great, thank you!
