### ISSUE TITLE
Fallback to previous devshell upon failure is unclear

### ISSUE THREAD

**Issue by amarshall** [nix-community/nix-direnv#486]
Since https://github.com/nix-community/nix-direnv/pull/420 (I believe), if loading the Nix devshell fails, the previous cached one is used. While I do not necessarily disagree with this behavior, I think that it should be much more clear that this is occuring, as currently one might see errors but think “well it loaded anyway, so those errors may not matter”, especially coupled with the fact that Nix *does* have non-fatal errors. Or the user might just miss those errors in a sea of other output or because they are in the flow. Either way, the shell ends up non-obviously in the “stale” state.

It may also make sense for it to be configurable whether to do this (and knowable from the outside, e.g. to condition on fallback having occurred in the `.envrc`).

**Comment by bbenne10** [comment]
1) I don't support configuring this behavior. We can discuss why if you want, but it boils down to "complex bash is hard to read and configuration increases code paths significantly". I don't *really* see the benefit of making this configurable if we make it **obvious**
2) I think that this is just adding an `else` block to the `if` surrounding the `print-dev-env` call [here](https://github.com/nix-community/nix-direnv/blob/master/direnvrc#L300)? I may get around to this soon, but PRs are definitely welcome.

**Comment by Mic92** [comment]
The current error message says "use_flake failed - Is your flake's devShell working?", but it doesn't say that it falls back to the previous devshell, which is what I think @amarshall is trying to say. I think the error message can be improved here.

**Comment by bbenne10** [comment]
That error message only happens if there is *no* profile_rc to fall back to, which means that there's no fallback shell at all. 

The problem is more nefarious than just that, since that is pretty clear: We couldn't evaluate your flake at all and so we failed with an error message. If we failed to evaluate your current flake, but there is a currently existing profile_rc, you'll never see that message. This means you'll implicitly end up in an old shell. 

I agree that we can improve on this, but that isn't the source of the issue (and this points at why I consistently push back against additional configuration - this is complex enough that even the two people that should know the code the best get lost in it even now!)

**Comment by Mic92** [comment]
> I’ve never seen this error. Using nix-direnv 3.0.4, direnv 2.32.3. I just changed a `flake.nix` to have a syntax error and it did not show that error upon reload.

Agreed there should be definitely an error every time and we shouldn't cache it. If this error message happen, why wouldn't than want to have a fallback configured?

**Comment by bbenne10** [comment]
> I’ve never seen this error. Using nix-direnv 3.0.4, direnv 2.32.3. I just changed a flake.nix to have a syntax error and it did not show that error upon reload.

That's because your flake has a fallback profile already :)

This is the behavior we need to clarify. Right now, we wait to invalidate the old shell until a new one loads properly. If it doesn't load properly, we silently fall into the outdated environment. If we don't have an outdated environment to fall into, we can't fall into *any* new environment and that is where the "is your flake's devShell working?" message comes from.

I think this particular case is pretty clear. "We tried to do a thing and couldn't do it *and we couldn't fall back to the old thing because it didn't exist*". The ambiguous case you're asking for a resolution to is "We tried to do the thing and couldn't, but we *did* find that we had an old iteration.  We loaded that iteration but didn't tell you anything about doing that other than the nix messages that got spit out above".

> Setting some env var in the else as well
Sure. That's both trivial to set up and trivial to consume in a user specific manner (not sure how one might handle that in a "global" way - say, in `~/.config/direnv/direnvrc` or something, though? But that doesn't mean we shouldn't do it)

**Comment by Patrick-Poitras** [comment]
Just as a note here, I managed to shoot my leg off with this footgun. Right now at least one upstream components doesn't handle this curveball fallback behaviours because nobody expects a build failure to default to a state that isn't "broken". Anything that relies on this was broken by #420, and the fact that it's unconfigurable at a user level means I have to go beg the packages that integrate with direnv to make an exception in the case of specifically nix-direnv for this reason.

See also:
https://github.com/purcell/envrc/issues/116

**Comment by Patrick-Poitras** [comment]
If people are using it in a more interactive mode, then are we forced to return a status 0 error code? It seems to me that returning something else while maintaining fallback behaviour could work. If someone is messing with their shell then they can handle error codes appropriately.

If the other thread is anything to go by, this should suffice to enable that downstream framework to function.

**Comment by bbenne10** [comment]
It is my understanding that any non-zero exit code from a plugin causes direnv to assume it has fully failed and not load the re-stultant environment. I haven't tested this explicitly though. I will do so tomorrow. 

This would mean that you simply cannot exit non-zero and get the environment to work.

**Comment by bbenne10** [comment]
In the future, please open a new issue rather than necroposting an old one.
[PR opened.](https://github.com/nix-community/nix-direnv/pull/605) Tests failing, but I'll get around to that after this weekend.
