### ISSUE TITLE
watch_file doesn't invalidate the cache

### ISSUE THREAD

**Issue by felixscheinost** [nix-community/nix-direnv#51]
I am trying to use `watch_file` to also reload the environment if a file that is imported in `shell.nix` changes.

### .envrc

```
use_nix
watch_file shell2.nix
```

### shell.nix 

```
import ./shell2.nix
```

### shell2.nix 

```
with (import <nixpkgs> {});
mkShell {
  buildInputs = [
    hello
  ];
}
```

## Test 

If I change `shell2.nix` and press enter `direnv` starts:

```
direnv: loading ~/Development/nix-direnv-test/.envrc
```

But `nix-direnv` says:

```
direnv: using cached derivation
```

I need to explicitly call `touch .envrc` to get the updated environment.

Can this be fixed?

**Comment by Mic92** [comment]
Not so easy. This is what we check write now: https://github.com/nix-community/nix-direnv/blob/master/direnvrc#L126
You could hack around by adding this to your `.envrc`:

```console
$ touch -r shell.nix shell2.nix
```

**Comment by Mic92** [comment]
I decided sacrify correctness here to improve performance. [lorri](https://github.com/target/lorri/) might handle this more gracefully.

**Comment by bb010g** [comment]
Would a possible solution be to implement the following via a Bash array, which would be extensible?

https://github.com/nix-community/nix-direnv/blob/adfca0d26dc687c1d10a4e88ef32cbc11bcaee47/direnvrc#L70-L76

I'd like to add `devshell.toml` to that set of files, but can't without vendoring `nix-direnv/direnvrc`.

**Comment by Mic92** [comment]
I guess it could be made extensible, but I think I would also accept `devshell.toml` in the default list.

**Comment by polygon** [comment]
I'm being affected by this as well. This package has its `devShell` inside another .nix-file. The `touch`-trick mentioned above works well enough for now since there is only one additional .nix-file but if the flake grows and more .nix-files are added, I see this becoming bit more of a pain.

Wondering if this could be done in a better way. Ideally, `direnv` would set a variable indicating that it was invoked due to a `watch_file` trigger firing. We could then add the test for this to the list above and trigger a rebuild. Might also require an upstream change to `direnv` (I've not checked) but may be worth it.

**Comment by polygon** [comment]
I made a suggestion on how this might be fixed here: https://github.com/nix-community/nix-direnv/pull/148
