### ISSUE TITLE
direnv reloads on every file timestamp change (even if file didnt change)

### ISSUE THREAD

**Issue by srghma** [nix-community/nix-direnv#531]
https://youtu.be/aSBCIlmdnac

**Comment by bbenne10** [comment]
[This is as intended.](https://github.com/nix-community/nix-direnv/blob/0d71ed4c4e98918e79bec02be48a66756a393884/direnvrc#L319)

**Comment by srghma** [comment]
I was just thinking maybe it's possible to use more intelligent approach

I have a bad habit of resaving file all the time in vim

Anyway, will just close, tnx

**Comment by bbenne10** [comment]
I am very sure that you could do it, but we have not (yet?). 
I suspect that the reasoning behind this is that the only thing that is invalidated in those cases in the `print-dev-env` output (the `profilerc` in nix-direnv parlance). That's relatively quick to re-create because the hard part (the downloading of the dependencies and creation of the environment), so I am not particularly motivated to pick up the "hash every file so that cache is only invalidated when those files change" task. 

I believe I haven't really noticed this because of some differences in the logic around how emacs saves files? I should go spend 10 minutes and figure out how that works and see if that's a common pattern.
