### ISSUE TITLE
How i could use nix-direnv but also set up custom functions?

### ISSUE THREAD

**Issue by Mdsp9070** [nix-community/nix-direnv#97]
I recently started to use `nix-direnv` but I think I'm doing some mistakes on how to set up and customize it.

I installed via `home-manager` as README says. So, going to `~/.config/direnv/direnvrc`, the content is:
```
source /nix/store/j0ai049yz9bjsxy423zppk0ipni1jdr0-nix-direnv-1.2.6/share/nix-direnv/direnvrc
```

But I want to create a `layout_postgres` functon to have a per project postgres. So I wrote it with `home-manager`:
```nix
  xdg.configFile.".direnvrc".text = ''
    #! /usr/bin/env nix-shelL
    #! nix-shell -i bash -p postgresql

    layout_postgres() {
      PGHOST=$(direnv_layout_dir)/.postgres
      PGHOST=$PGHOST/data
      PGLOG=$PGHOST/postgres.log
      PGUSER=postgres
      export PGPASSWORD=postgres

      is_running() {
        pg_ctl status 2>/dev/null | grep "server is running" 1>/dev/null
      }

      if [[ ! -d "$PGDATA" ]]; then
        echo 'Initializing postgresql daemon...'
        initdb -auth=trust --no-locale --encoding=UTF8 >/dev/null

        echo "unix_socket_directories = '$PGHOST'" | \
          "$PGDATA/postgresql.conf"

        echo "CREATE DATABASE $PGUSER;" | postgres --single -E postgres
      fi

      if ! is_running; then
        pg_ctl start -l $PGLOG 
      fi

      finish() {
        pg_ctl -D $PGDATA stop  
      }

      trap finish EXIT
    }
  '';
```

what Iḿ doing wrongly?

**Comment by Mdsp9070** [comment]
oh, i was setting the `direnvrc` xdg path in a wrong way....

setting to `direnv/direnvrc` it merges the source of `nix-direnv` and my functions

**Comment by Mic92** [comment]
What is the resulting direnvrc that you ended up with after adding the custom to home-manager? Did you use the home-manager option to enable direnv?

**Comment by Mdsp9070** [comment]
yes! I used as:
```nix
programs = {
    direnv = {
      enable = true;
      nix-direnv.enable = true;
    };
  };
```

and my resulting `direnvrc`:
```sh
source /nix/store/j0ai049yz9bjsxy423zppk0ipni1jdr0-nix-direnv-1.2.6/share/nix-direnv/direnvrc
#! /usr/bin/env nix-shelL
#! nix-shell -i bash -p postgresql

layout_postgres() {
  echo "direnv: usign layout postgres"

  export PGHOST=$(direnv_layout_dir)/.postgres
  export PGDATA=$PGHOST/data
  export PGLOG=$PGHOST/postgres.log
  export PGUSER=postgres
  export PGPASSWORD=postgres

  if [[ ! -d "$PGDATA" ]]; then
    echo 'Initializing postgresql daemon...'
    initdb --auth=trust --no-locale --encoding=UTF8 \
      -U=$PGHOST -D=$PGDATA >/dev/null

    echo "unix_socket_directories = '$PGHOST'" >> "$PGDATA/postgresql.conf"

    echo "CREATE DATABASE $PGUSER;" | postgres --single -E postgres
  fi
}
```

now I'm trying to not make direnv get stuck with postgres server start

**Comment by bbenne10** [comment]
Honestly, just use numtide's devShell (or devenv, I suppose, but I am unfamiliar with devenv entirely) and include their postgres service helper. Yes, it is a manual invocation and takes over a whole terminal window (unless explicitly backgrounded), but it is a much simpler solution than trying to figure out how to handle the corner cases implicit in the automatic solutions (how do you ensure only one postgres is started if you CD into the environment in independent shell sessions? What happens if postgres dies? How do you clean the data directory up after the fact since direnv doesn't have unload hooks? Etc etc etc)

Shell hooks aren't really FOR this. It would behoove you to use a manual tool that works better. It isn't THAT much work to handle manually in my experience.

**Comment by Mic92** [comment]
Or use process-compose: https://github.com/F1bonacc1/process-compose
